global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 5
   publish_frequency: 4
   static_map: true
   rolling_window: false
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
