local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5
   publish_frequency: 4
   static_map: true
   rolling_window: false
   width: 6.0
   height: 6.0
   resolution: 0.01
   transform_tolerance: 1.0
